apiVersion: v1
kind: Service
metadata:
  name: laas-images-load-balancer
spec:
  selector:
    app: llama-as-a-service-images-api
  ports:
    - port: 80
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-as-a-service-images-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laas-images-service
  template:
    metadata:
      labels:
        app: laas-images-service
    spec:
      containers:
        - name:  laas-images-service
          image: ghcr.io/llama-as-a-service/images-service:0.2.1
          imagePullPolicy: Always #Never
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: '4000'
            - name: MONGO_URI
              value: mongodb+srv://admin:IPo1NiAah7L1@laascluster.aknzi.mongodb.net/?retryWrites=true&w=majority