apiVersion: v1
kind: Service
metadata:
  name: laas-gateway-load-balancer
spec:
  selector:
    app:  llama-as-a-service-gateway-api
  ports:
    - port: 80
      targetPort: 8888
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-as-a-service-gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laas-gateway-service
  template:
    metadata:
      labels:
        app: laas-gateway-service
    spec:
      containers:
        - name:  laas-gateway-service
          image: ghcr.io/llama-as-a-service/gateway-service:0.3.2
          imagePullPolicy: Always #Never
          ports:
            - containerPort: 8888
          env:
            - name: PORT
              value: '8888'
            - name: JWT_TOKEN_KEY
              value: 250830985034809wfsfg
            - name: API_IMAGES_URL
              value: http://laas-images-service